<a href="https://colab.research.google.com/github/ashiibansal/machine-learning-lab/blob/main/Lab3/Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Apply descriptive statistical techniques to summarize and interpret datasets

In [3]:
import pandas as pd

columns = [
    "Class",
    "Alcohol",
    "Malic_Acid",
    "Ash",
    "Alcalinity_of_Ash",
    "Magnesium",
    "Total_Phenols",
    "Flavanoids",
    "Nonflavanoid_Phenols",
    "Proanthocyanins",
    "Color_Intensity",
    "Hue",
    "OD280_OD315",
    "Proline"
]

df = pd.read_csv("wine.data", header=None, names=columns)

### Mean (Average)

The mean represents the average value of each chemical attribute across all wine samples.

In [4]:
df.mean()

Class                     1.938202
Alcohol                  13.000618
Malic_Acid                2.336348
Ash                       2.366517
Alcalinity_of_Ash        19.494944
Magnesium                99.741573
Total_Phenols             2.295112
Flavanoids                2.029270
Nonflavanoid_Phenols      0.361854
Proanthocyanins           1.590899
Color_Intensity           5.058090
Hue                       0.957449
OD280_OD315               2.611685
Proline                 746.893258
dtype: float64

### Median (Middle Value)

The median shows the central tendency and is less affected by extreme values compared to the mean.

In [5]:
df.median()

Class                     2.000
Alcohol                  13.050
Malic_Acid                1.865
Ash                       2.360
Alcalinity_of_Ash        19.500
Magnesium                98.000
Total_Phenols             2.355
Flavanoids                2.135
Nonflavanoid_Phenols      0.340
Proanthocyanins           1.555
Color_Intensity           4.690
Hue                       0.965
OD280_OD315               2.780
Proline                 673.500
dtype: float64

### Mode (Most Frequent Value)

The mode represents the most frequently occurring value in each feature. It is useful for identifying common measurements.

In [6]:
df.mode()

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0,2.0,12.37,1.73,2.28,20.0,88.0,2.2,2.65,0.26,1.35,2.6,1.04,2.87,520.0
1,NaN,13.05,NaN,2.30,NaN,NaN,NaN,NaN,0.43,NaN,3.8,NaN,NaN,680.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6,NaN,NaN,NaN

### Minimum and Maximum

In [8]:
df.min()

Class                     1.00
Alcohol                  11.03
Malic_Acid                0.74
Ash                       1.36
Alcalinity_of_Ash        10.60
Magnesium                70.00
Total_Phenols             0.98
Flavanoids                0.34
Nonflavanoid_Phenols      0.13
Proanthocyanins           0.41
Color_Intensity           1.28
Hue                       0.48
OD280_OD315               1.27
Proline                 278.00
dtype: float64

In [9]:
df.max()

Class                      3.00
Alcohol                   14.83
Malic_Acid                 5.80
Ash                        3.23
Alcalinity_of_Ash         30.00
Magnesium                162.00
Total_Phenols              3.88
Flavanoids                 5.08
Nonflavanoid_Phenols       0.66
Proanthocyanins            3.58
Color_Intensity           13.00
Hue                        1.71
OD280_OD315                4.00
Proline                 1680.00
dtype: float64

### Sum

In [10]:
df.sum()

Class                      345.000000
Alcohol                   2314.110000
Malic_Acid                 415.870000
Ash                        421.240000
Alcalinity_of_Ash         3470.100000
Magnesium                17754.000000
Total_Phenols              408.530000
Flavanoids                 361.210000
Nonflavanoid_Phenols        64.410000
Proanthocyanins            283.180000
Color_Intensity            900.339999
Hue                        170.426000
OD280_OD315                464.880000
Proline                 132947.000000
dtype: float64

### Standard Deviation (Spread of Data)

Standard deviation measures how much the data varies from the mean. Higher values indicate greater variability among wine samples.

In [11]:
df.std()

Class                     0.775035
Alcohol                   0.811827
Malic_Acid                1.117146
Ash                       0.274344
Alcalinity_of_Ash         3.339564
Magnesium                14.282484
Total_Phenols             0.625851
Flavanoids                0.998859
Nonflavanoid_Phenols      0.124453
Proanthocyanins           0.572359
Color_Intensity           2.318286
Hue                       0.228572
OD280_OD315               0.709990
Proline                 314.907474
dtype: float64

###  Quartiles & Percentiles

In [12]:
df.quantile([0.25, 0.5, 0.75])

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0.25,1.0,12.3625,1.6025,2.2100,17.2,88.0,1.7425,1.205,0.2700,1.250,3.22,0.7825,1.9375,500.5
0.50,2.0,13.0500,1.8650,2.3600,19.5,98.0,2.3550,2.135,0.3400,1.555,4.69,0.9650,2.7800,673.5
0.75,3.0,13.6775,3.0825,2.5575,21.5,107.0,2.8000,2.875,0.4375,1.950,6.20,1.1200,3.1700,985.0

In [13]:
df.quantile([0.10, 0.90])

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
0.1,1.0,11.933,1.247,2.0,16.0,85.0,1.471,0.607,0.217,0.854,2.549,0.610,1.580,406.7
0.9,3.0,14.100,3.983,2.7,24.0,118.0,3.044,3.233,0.530,2.305,8.530,1.233,3.456,1261.5

### Combined Statistical Summary

In [14]:
df.describe()

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,1.938202,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.775035,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,1.000000,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,1.000000,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,2.000000,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,3.000000,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,3.000000,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [15]:
df.corr()

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
Class,1.000000,-0.328222,0.437776,-0.049643,0.517859,-0.209179,-0.719163,-0.847498,0.489109,-0.499130,0.265668,-0.617369,-0.788230,-0.633717
Alcohol,-0.328222,1.000000,0.094397,0.211545,-0.310235,0.270798,0.289101,0.236815,-0.155929,0.136698,0.546364,-0.071747,0.072343,0.643720
Malic_Acid,0.437776,0.094397,1.000000,0.164045,0.288500,-0.054575,-0.335167,-0.411007,0.292977,-0.220746,0.248985,-0.561296,-0.368710,-0.192011
Ash,-0.049643,0.211545,0.164045,1.000000,0.443367,0.286587,0.128980,0.115077,0.186230,0.009652,0.258887,-0.074667,0.003911,0.223626
Alcalinity_of_Ash,0.517859,-0.310235,0.288500,0.443367,1.000000,-0.083333,-0.321113,-0.351370,0.361922,-0.197327,0.018732,-0.273955,-0.276769,-0.440597
Magnesium,-0.209179,0.270798,-0.054575,0.286587,-0.083333,1.000000,0.214401,0.195784,-0.256294,0.236441,0.199950,0.055398,0.066004,0.393351
Total_Phenols,-0.719163,0.289101,-0.335167,0.128980,-0.321113,0.214401,1.000000,0.864564,-0.449935,0.612413,-0.055136,0.433681,0.699949,0.498115
Flavanoids,-0.847498,0.236815,-0.411007,0.115077,-0.351370,0.195784,0.864564,1.000000,-0.537900,0.652692,-0.172379,0.543479,0.787194,0.494193
Nonflavanoid_Phenols,0.489109,-0.155929,0.292977,0.186230,0.361922,-0.256294,-0.449935,-0.537900,1.000000,-0.365845,0.139057,-0.262640,-0.503270,-0.311385
Proanthocyanins,-0.499130,0.136698,-0.220746,0.009652,-0.197327,0.236441,0.612413,0.652692,-0.365845,1.000000,-0.025250,0.295544,0.519067,0.330417
Color_Intensity,0.265668,0.546364,0.248985,0.258887,0.018732,0.199950,-0.055136,-0.172379,0.139057,-0.025250,1.000000,-0.521813,-0.428815,0.316100
Hue,-0.617369,-0.071747,-0.561296,-0.074667,-0.273955,0.055398,0.433681,0.543479,-0.262640,0.295544,-0.521813,1.000000,0.565468,0.236183
OD280_OD315,-0.788230,0.072343,-0.368710,0.003911,-0.276769,0.066004,0.699949,0.787194,-0.503270,0.519067,-0.428815,0.565468,1.000000,0.312761
Proline,-0.633717,0.643720,-0.192011,0.223626,-0.440597,0.393351,0.498115,0.494193,-0.311385,0.330417,0.316100,0.236183,0.312761,1.000000

In [16]:
df.cov()

,Class,Alcohol,Malic_Acid,Ash,Alcalinity_of_Ash,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280_OD315,Proline
Class,0.600679,-0.206515,0.379039,-0.010555,1.340364,-2.315495,-0.348835,-0.656091,0.047177,-0.221413,0.477339,-0.109368,-0.433737,-154.667651
Alcohol,-0.206515,0.659062,0.085611,0.047115,-0.841093,3.139878,0.146887,0.192033,-0.015754,0.063518,1.028283,-0.013313,0.041698,164.567185
Malic_Acid,0.379039,0.085611,1.248015,0.050277,1.076332,-0.870780,-0.234338,-0.458630,0.040733,-0.141147,0.644838,-0.143326,-0.292447,-67.548867
Ash,-0.010555,0.047115,0.050277,0.075265,0.406208,1.122937,0.022146,0.031535,0.006358,0.001516,0.164654,-0.004682,0.000762,19.319739
Alcalinity_of_Ash,1.340364,-0.841093,1.076332,0.406208,11.152686,-3.974760,-0.671149,-1.172083,0.150422,-0.377176,0.145024,-0.209118,-0.656234,-463.355345
Magnesium,-2.315495,3.139878,-0.870780,1.122937,-3.974760,203.989335,1.916470,2.793087,-0.455563,1.932832,6.620521,0.180851,0.669308,1769.158700
Total_Phenols,-0.348835,0.146887,-0.234338,0.022146,-0.671149,1.916470,0.391690,0.540470,-0.035045,0.219373,-0.079998,0.062039,0.311021,98.171057
Flavanoids,-0.656091,0.192033,-0.458630,0.031535,-1.172083,2.793087,0.540470,0.997719,-0.066867,0.373148,-0.399169,0.124082,0.558262,155.447492
Nonflavanoid_Phenols,0.047177,-0.015754,0.040733,0.006358,0.150422,-0.455563,-0.035045,-0.066867,0.015489,-0.026060,0.040121,-0.007471,-0.044469,-12.203586
Proanthocyanins,-0.221413,0.063518,-0.141147,0.001516,-0.377176,1.932832,0.219373,0.373148,-0.026060,0.327595,-0.033504,0.038665,0.210933,59.554334
Color_Intensity,0.477339,1.028283,0.644838,0.164654,0.145024,6.620521,-0.079998,-0.399169,0.040121,-0.033504,5.374449,-0.276506,-0.705813,230.767480
Hue,-0.109368,-0.013313,-0.143326,-0.004682,-0.209118,0.180851,0.062039,0.124082,-0.007471,0.038665,-0.276506,0.052245,0.091766,17.000223
OD280_OD315,-0.433737,0.041698,-0.292447,0.000762,-0.656234,0.669308,0.311021,0.558262,-0.044469,0.210933,-0.705813,0.091766,0.504086,69.927526
Proline,-154.667651,164.567185,-67.548867,19.319739,-463.355345,1769.158700,98.171057,155.447492,-12.203586,59.554334,230.767480,17.000223,69.927526,99166.717355